# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171122_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerprofile',
            old_name='sevice',
            new_name='service',
        ),
    ]
