# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20171122_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(choices=[('FL', 'Film'), ('DG', 'Digital'), ('PL', 'Polaroid'), ('DG', 'Daguerreotype')], max_length=2),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=models.CharField(choices=[('PR', 'Portrait'), ('SL', 'Still Life'), ('NT', 'Nature'), ('AB', 'Abstract'), ('FS', 'Fashion'), ('AD', 'Advertising'), ('WL', 'Wildlife'), ('WD', 'Wedding'), ('BW', 'Black and White'), ('MC', 'Macro'), ('TP', 'Time Lapse'), ('LS', 'Landscape'), ('SP', 'Sports')], max_length=2),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='service',
            field=models.CharField(choices=[('SS', 'Session'), ('ED', 'Editing'), ('CL', 'Coloring'), ('PT', 'Printing'), ('FR', 'Framing'), ('AV', 'Advertising'), ('TV', 'Travel')], max_length=2),
        ),
    ]
